services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      - HOST=0.0.0.0
      - NEXT_PUBLIC_API_URL=https://djangifybackend.up.railway.app
      - NEXT_PUBLIC_DJANGO_URL=https://djangifybackend.up.railway.app
